// rag.proto —— RAG 检索与知识库管理服务契约（P3-A）
//
// 本文件是 RAG 域的唯一事实来源：
//   - rag-service 实现它（backend/internal/rag/server.go）；
//   - 智能体经 kb_search 工具（L1 只读）调用 Search，结果注入对话并带引用；
//   - 管理端（gateway adminsvc kb 模块）调用 CRUD / 摄取 RPC，再包成 REST。
//
// 设计要点（对外黑盒）：
//   - Search 走混合检索（向量 hnsw + pg_trgm 关键词双路召回 + RRF 融合），
//     内部实现可整体替换（EmbeddingProvider/Chunker/Retriever 均为插拔接口）；
//   - 阶段3·多租户：Search 按 agent_id 限定资源域——智能体调用方（kb_search 工具）
//     必须携带自身 agent_id，越出本域的 kb_ids 一律 404，防跨域检索泄露；
//   - Rerank 精排二期接入，Search 返回的 score 字段已预留语义（一期=融合分）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestStatus 文档摄取状态机（queued → processing → succeeded|failed）。
type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED IngestStatus = 0
	IngestStatus_QUEUED                    IngestStatus = 1
	IngestStatus_PROCESSING                IngestStatus = 2
	IngestStatus_SUCCEEDED                 IngestStatus = 3
	IngestStatus_FAILED                    IngestStatus = 4
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "QUEUED",
		2: "PROCESSING",
		3: "SUCCEEDED",
		4: "FAILED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED": 0,
		"QUEUED":                    1,
		"PROCESSING":                2,
		"SUCCEEDED":                 3,
		"FAILED":                    4,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_v1_rag_proto_enumTypes[0].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_rag_v1_rag_proto_enumTypes[0]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

// Chunk 检索命中的内容片段（带来源引用）。
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	KbId          string                 `protobuf:"bytes,3,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	KbName        string                 `protobuf:"bytes,4,opt,name=kb_name,json=kbName,proto3" json:"kb_name,omitempty"`                                                                 // 冗余便于展示
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 片段文本
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                                                                               // 引用溯源：文件名（可含页码/章节）
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`                                                                               // 融合分（一期=RRF 融合后分）
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 文档元数据（标题/作者/章节等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Chunk) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Chunk) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *Chunk) GetKbName() string {
	if x != nil {
		return x.KbName
	}
	return ""
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Chunk) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Chunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                         // 检索语句
	KbIds         []string               `protobuf:"bytes,2,rep,name=kb_ids,json=kbIds,proto3" json:"kb_ids,omitempty"`            // 空 = 按 agent_id 域内全部知识库
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`              // 返回条数（默认 5，上限 20）
	MinScore      float64                `protobuf:"fixed64,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"` // 相似度阈值（0~1，默认 0 不过滤）
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`      // 调用方资源域（阶段3·多租户隔离）：
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetKbIds() []string {
	if x != nil {
		return x.KbIds
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *SearchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type KnowledgeBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 形如 kb_xxx
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DocCount      int32                  `protobuf:"varint,4,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`    // 文档数（含失败）
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix 秒
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AgentId       string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 所属智能体域（阶段3·多租户）
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`               // 启用状态（false = 停用，不可被会话/普通用户检索引用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeBase) Reset() {
	*x = KnowledgeBase{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBase) ProtoMessage() {}

func (x *KnowledgeBase) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBase.ProtoReflect.Descriptor instead.
func (*KnowledgeBase) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeBase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBase) GetDocCount() int32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *KnowledgeBase) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KnowledgeBase) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *KnowledgeBase) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KnowledgeBase) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateKBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                      // 1~50 字符
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`        // ≤200 字符
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 所属智能体域（阶段3；空 = 按调用方默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKBRequest) Reset() {
	*x = CreateKBRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKBRequest) ProtoMessage() {}

func (x *CreateKBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKBRequest.ProtoReflect.Descriptor instead.
func (*CreateKBRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKBRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKBRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKBRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// ListKBRequest 列表知识库。
// agent_id 空 = 全部；非空 = 仅该智能体域。
type ListKBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKBRequest) Reset() {
	*x = ListKBRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKBRequest) ProtoMessage() {}

func (x *ListKBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKBRequest.ProtoReflect.Descriptor instead.
func (*ListKBRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *ListKBRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListKBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bases         []*KnowledgeBase       `protobuf:"bytes,1,rep,name=bases,proto3" json:"bases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKBResponse) Reset() {
	*x = ListKBResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKBResponse) ProtoMessage() {}

func (x *ListKBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKBResponse.ProtoReflect.Descriptor instead.
func (*ListKBResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *ListKBResponse) GetBases() []*KnowledgeBase {
	if x != nil {
		return x.Bases
	}
	return nil
}

type UpdateKBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // 知识库 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 新名称（1~50 字符）
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 新描述（≤200 字符）
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`  // 新启用状态（不传 = 保持原状，避免旧客户端误停用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKBRequest) Reset() {
	*x = UpdateKBRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKBRequest) ProtoMessage() {}

func (x *UpdateKBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKBRequest.ProtoReflect.Descriptor instead.
func (*UpdateKBRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateKBRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKBRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKBRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateKBRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type DeleteKBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKBRequest) Reset() {
	*x = DeleteKBRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKBRequest) ProtoMessage() {}

func (x *DeleteKBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKBRequest.ProtoReflect.Descriptor instead.
func (*DeleteKBRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteKBRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKBResponse) Reset() {
	*x = DeleteKBResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKBResponse) ProtoMessage() {}

func (x *DeleteKBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKBResponse.ProtoReflect.Descriptor instead.
func (*DeleteKBResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

type DocumentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	KbId          string                 `protobuf:"bytes,2,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Status        IngestStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=rag.v1.IngestStatus" json:"status,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,5,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // failed 时原因
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentStatus) Reset() {
	*x = DocumentStatus{}
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStatus) ProtoMessage() {}

func (x *DocumentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStatus.ProtoReflect.Descriptor instead.
func (*DocumentStatus) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *DocumentStatus) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocumentStatus) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *DocumentStatus) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentStatus) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *DocumentStatus) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *DocumentStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DocumentStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DocumentStatus) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpsertDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 含扩展名（唯一索引 (kb_id, file_name)）
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                   // 原始文件字节
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // md | txt | html | pdf | docx（空 = 按扩展名推断）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDocumentRequest) Reset() {
	*x = UpsertDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocumentRequest) ProtoMessage() {}

func (x *UpsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertDocumentRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *UpsertDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UpsertDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpsertDocumentRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UpsertDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *DocumentStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDocumentResponse) Reset() {
	*x = UpsertDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocumentResponse) ProtoMessage() {}

func (x *UpsertDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpsertDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertDocumentResponse) GetStatus() *DocumentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 从 1 开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 默认 20，上限 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{13}
}

func (x *ListDocumentsRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentStatus      `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{14}
}

func (x *ListDocumentsResponse) GetDocuments() []*DocumentStatus {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{16}
}

type RetryDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 文档 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDocumentRequest) Reset() {
	*x = RetryDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDocumentRequest) ProtoMessage() {}

func (x *RetryDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDocumentRequest.ProtoReflect.Descriptor instead.
func (*RetryDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{17}
}

func (x *RetryDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentStatusRequest) Reset() {
	*x = GetDocumentStatusRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentStatusRequest) ProtoMessage() {}

func (x *GetDocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{18}
}

func (x *GetDocumentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\xa5\x02\n" +
	"\x05Chunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x13\n" +
	"\x05kb_id\x18\x03 \x01(\tR\x04kbId\x12\x17\n" +
	"\akb_name\x18\x04 \x01(\tR\x06kbName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x127\n" +
	"\bmetadata\x18\b \x03(\v2\x1b.rag.v1.Chunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x15\n" +
	"\x06kb_ids\x18\x02 \x03(\tR\x05kbIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x01R\bminScore\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x06chunks\x18\x01 \x03(\v2\r.rag.v1.ChunkR\x06chunks\"\xe5\x01\n" +
	"\rKnowledgeBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoc_count\x18\x04 \x01(\x05R\bdocCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"b\n" +
	"\x0fCreateKBRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"*\n" +
	"\rListKBRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"=\n" +
	"\x0eListKBResponse\x12+\n" +
	"\x05bases\x18\x01 \x03(\v2\x15.rag.v1.KnowledgeBaseR\x05bases\"\x82\x01\n" +
	"\x0fUpdateKBRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"!\n" +
	"\x0fDeleteKBRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10DeleteKBResponse\"\xfc\x01\n" +
	"\x0eDocumentStatus\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x13\n" +
	"\x05kb_id\x18\x02 \x01(\tR\x04kbId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.rag.v1.IngestStatusR\x06status\x12\x1f\n" +
	"\vchunk_count\x18\x05 \x01(\x05R\n" +
	"chunkCount\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x80\x01\n" +
	"\x15UpsertDocumentRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"H\n" +
	"\x16UpsertDocumentResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.rag.v1.DocumentStatusR\x06status\"\\\n" +
	"\x14ListDocumentsRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\x15ListDocumentsResponse\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.rag.v1.DocumentStatusR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteDocumentResponse\"&\n" +
	"\x14RetryDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18GetDocumentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*d\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xe8\x05\n" +
	"\n" +
	"RagService\x127\n" +
	"\x06Search\x12\x15.rag.v1.SearchRequest\x1a\x16.rag.v1.SearchResponse\x12E\n" +
	"\x13CreateKnowledgeBase\x12\x17.rag.v1.CreateKBRequest\x1a\x15.rag.v1.KnowledgeBase\x12C\n" +
	"\x12ListKnowledgeBases\x12\x15.rag.v1.ListKBRequest\x1a\x16.rag.v1.ListKBResponse\x12E\n" +
	"\x13UpdateKnowledgeBase\x12\x17.rag.v1.UpdateKBRequest\x1a\x15.rag.v1.KnowledgeBase\x12H\n" +
	"\x13DeleteKnowledgeBase\x12\x17.rag.v1.DeleteKBRequest\x1a\x18.rag.v1.DeleteKBResponse\x12O\n" +
	"\x0eUpsertDocument\x12\x1d.rag.v1.UpsertDocumentRequest\x1a\x1e.rag.v1.UpsertDocumentResponse\x12L\n" +
	"\rListDocuments\x12\x1c.rag.v1.ListDocumentsRequest\x1a\x1d.rag.v1.ListDocumentsResponse\x12E\n" +
	"\rRetryDocument\x12\x1c.rag.v1.RetryDocumentRequest\x1a\x16.rag.v1.DocumentStatus\x12O\n" +
	"\x0eDeleteDocument\x12\x1d.rag.v1.DeleteDocumentRequest\x1a\x1e.rag.v1.DeleteDocumentResponse\x12M\n" +
	"\x11GetDocumentStatus\x12 .rag.v1.GetDocumentStatusRequest\x1a\x16.rag.v1.DocumentStatusB@Z>github.com/Steve5201/agent-backend/internal/proto/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rag_v1_rag_proto_goTypes = []any{
	(IngestStatus)(0),                // 0: rag.v1.IngestStatus
	(*Chunk)(nil),                    // 1: rag.v1.Chunk
	(*SearchRequest)(nil),            // 2: rag.v1.SearchRequest
	(*SearchResponse)(nil),           // 3: rag.v1.SearchResponse
	(*KnowledgeBase)(nil),            // 4: rag.v1.KnowledgeBase
	(*CreateKBRequest)(nil),          // 5: rag.v1.CreateKBRequest
	(*ListKBRequest)(nil),            // 6: rag.v1.ListKBRequest
	(*ListKBResponse)(nil),           // 7: rag.v1.ListKBResponse
	(*UpdateKBRequest)(nil),          // 8: rag.v1.UpdateKBRequest
	(*DeleteKBRequest)(nil),          // 9: rag.v1.DeleteKBRequest
	(*DeleteKBResponse)(nil),         // 10: rag.v1.DeleteKBResponse
	(*DocumentStatus)(nil),           // 11: rag.v1.DocumentStatus
	(*UpsertDocumentRequest)(nil),    // 12: rag.v1.UpsertDocumentRequest
	(*UpsertDocumentResponse)(nil),   // 13: rag.v1.UpsertDocumentResponse
	(*ListDocumentsRequest)(nil),     // 14: rag.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),    // 15: rag.v1.ListDocumentsResponse
	(*DeleteDocumentRequest)(nil),    // 16: rag.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),   // 17: rag.v1.DeleteDocumentResponse
	(*RetryDocumentRequest)(nil),     // 18: rag.v1.RetryDocumentRequest
	(*GetDocumentStatusRequest)(nil), // 19: rag.v1.GetDocumentStatusRequest
	nil,                              // 20: rag.v1.Chunk.MetadataEntry
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	20, // 0: rag.v1.Chunk.metadata:type_name -> rag.v1.Chunk.MetadataEntry
	1,  // 1: rag.v1.SearchResponse.chunks:type_name -> rag.v1.Chunk
	4,  // 2: rag.v1.ListKBResponse.bases:type_name -> rag.v1.KnowledgeBase
	0,  // 3: rag.v1.DocumentStatus.status:type_name -> rag.v1.IngestStatus
	11, // 4: rag.v1.UpsertDocumentResponse.status:type_name -> rag.v1.DocumentStatus
	11, // 5: rag.v1.ListDocumentsResponse.documents:type_name -> rag.v1.DocumentStatus
	2,  // 6: rag.v1.RagService.Search:input_type -> rag.v1.SearchRequest
	5,  // 7: rag.v1.RagService.CreateKnowledgeBase:input_type -> rag.v1.CreateKBRequest
	6,  // 8: rag.v1.RagService.ListKnowledgeBases:input_type -> rag.v1.ListKBRequest
	8,  // 9: rag.v1.RagService.UpdateKnowledgeBase:input_type -> rag.v1.UpdateKBRequest
	9,  // 10: rag.v1.RagService.DeleteKnowledgeBase:input_type -> rag.v1.DeleteKBRequest
	12, // 11: rag.v1.RagService.UpsertDocument:input_type -> rag.v1.UpsertDocumentRequest
	14, // 12: rag.v1.RagService.ListDocuments:input_type -> rag.v1.ListDocumentsRequest
	18, // 13: rag.v1.RagService.RetryDocument:input_type -> rag.v1.RetryDocumentRequest
	16, // 14: rag.v1.RagService.DeleteDocument:input_type -> rag.v1.DeleteDocumentRequest
	19, // 15: rag.v1.RagService.GetDocumentStatus:input_type -> rag.v1.GetDocumentStatusRequest
	3,  // 16: rag.v1.RagService.Search:output_type -> rag.v1.SearchResponse
	4,  // 17: rag.v1.RagService.CreateKnowledgeBase:output_type -> rag.v1.KnowledgeBase
	7,  // 18: rag.v1.RagService.ListKnowledgeBases:output_type -> rag.v1.ListKBResponse
	4,  // 19: rag.v1.RagService.UpdateKnowledgeBase:output_type -> rag.v1.KnowledgeBase
	10, // 20: rag.v1.RagService.DeleteKnowledgeBase:output_type -> rag.v1.DeleteKBResponse
	13, // 21: rag.v1.RagService.UpsertDocument:output_type -> rag.v1.UpsertDocumentResponse
	15, // 22: rag.v1.RagService.ListDocuments:output_type -> rag.v1.ListDocumentsResponse
	11, // 23: rag.v1.RagService.RetryDocument:output_type -> rag.v1.DocumentStatus
	17, // 24: rag.v1.RagService.DeleteDocument:output_type -> rag.v1.DeleteDocumentResponse
	11, // 25: rag.v1.RagService.GetDocumentStatus:output_type -> rag.v1.DocumentStatus
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	file_rag_v1_rag_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		EnumInfos:         file_rag_v1_rag_proto_enumTypes,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
