// rag.proto —— RAG 检索与知识库管理服务契约（P3-A）
//
// 本文件是 RAG 域的唯一事实来源：
//   - rag-service 实现它（backend/internal/rag/server.go）；
//   - 智能体经 kb_search 工具（L1 只读）调用 Search，结果注入对话并带引用；
//   - 管理端（gateway adminsvc kb 模块）调用 CRUD / 摄取 RPC，再包成 REST。
//
// 设计要点（对外黑盒）：
//   - Search 走混合检索（向量 hnsw + pg_trgm 关键词双路召回 + RRF 融合），
//     内部实现可整体替换（EmbeddingProvider/Chunker/Retriever 均为插拔接口）；
//   - 阶段3·多租户：Search 按 agent_id 限定资源域——智能体调用方（kb_search 工具）
//     必须携带自身 agent_id，越出本域的 kb_ids 一律 404，防跨域检索泄露；
//   - Rerank 精排二期接入，Search 返回的 score 字段已预留语义（一期=融合分）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.13.0
// source: rag/v1/rag.proto

package ragv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_Search_FullMethodName              = "/rag.v1.RagService/Search"
	RagService_CreateKnowledgeBase_FullMethodName = "/rag.v1.RagService/CreateKnowledgeBase"
	RagService_ListKnowledgeBases_FullMethodName  = "/rag.v1.RagService/ListKnowledgeBases"
	RagService_UpdateKnowledgeBase_FullMethodName = "/rag.v1.RagService/UpdateKnowledgeBase"
	RagService_DeleteKnowledgeBase_FullMethodName = "/rag.v1.RagService/DeleteKnowledgeBase"
	RagService_UpsertDocument_FullMethodName      = "/rag.v1.RagService/UpsertDocument"
	RagService_ListDocuments_FullMethodName       = "/rag.v1.RagService/ListDocuments"
	RagService_RetryDocument_FullMethodName       = "/rag.v1.RagService/RetryDocument"
	RagService_DeleteDocument_FullMethodName      = "/rag.v1.RagService/DeleteDocument"
	RagService_GetDocumentStatus_FullMethodName   = "/rag.v1.RagService/GetDocumentStatus"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RagService RAG 检索与知识库管理服务。
type RagServiceClient interface {
	// Search 混合检索：向量 + 关键词双路召回，返回带来源引用的 chunk 列表。
	// kb_ids 为空 = 搜索全部知识库。
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// CreateKnowledgeBase 创建知识库。
	CreateKnowledgeBase(ctx context.Context, in *CreateKBRequest, opts ...grpc.CallOption) (*KnowledgeBase, error)
	// ListKnowledgeBases 列出全部知识库（含文档统计）。
	ListKnowledgeBases(ctx context.Context, in *ListKBRequest, opts ...grpc.CallOption) (*ListKBResponse, error)
	// UpdateKnowledgeBase 更新知识库名称/描述。
	UpdateKnowledgeBase(ctx context.Context, in *UpdateKBRequest, opts ...grpc.CallOption) (*KnowledgeBase, error)
	// DeleteKnowledgeBase 删除知识库（连带文档与全部 chunk）。
	DeleteKnowledgeBase(ctx context.Context, in *DeleteKBRequest, opts ...grpc.CallOption) (*DeleteKBResponse, error)
	// UpsertDocument 提交文档（原始字节落库待摄取）。同文件重传按 content_hash
	// 增量去重：内容未变则幂等跳过，变了则替换文档并重建其 chunk。
	UpsertDocument(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*UpsertDocumentResponse, error)
	// ListDocuments 列出知识库文档（含摄取状态，分页）。
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	// RetryDocument 手动重试摄取失败/已就绪的文档（重置 attempt 与退避，重新入队）。
	RetryDocument(ctx context.Context, in *RetryDocumentRequest, opts ...grpc.CallOption) (*DocumentStatus, error)
	// DeleteDocument 删除文档（连带全部 chunk）。
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	// GetDocumentStatus 查询单个文档摄取状态。
	GetDocumentStatus(ctx context.Context, in *GetDocumentStatusRequest, opts ...grpc.CallOption) (*DocumentStatus, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RagService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) CreateKnowledgeBase(ctx context.Context, in *CreateKBRequest, opts ...grpc.CallOption) (*KnowledgeBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBase)
	err := c.cc.Invoke(ctx, RagService_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListKnowledgeBases(ctx context.Context, in *ListKBRequest, opts ...grpc.CallOption) (*ListKBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKBResponse)
	err := c.cc.Invoke(ctx, RagService_ListKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpdateKnowledgeBase(ctx context.Context, in *UpdateKBRequest, opts ...grpc.CallOption) (*KnowledgeBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBase)
	err := c.cc.Invoke(ctx, RagService_UpdateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteKnowledgeBase(ctx context.Context, in *DeleteKBRequest, opts ...grpc.CallOption) (*DeleteKBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKBResponse)
	err := c.cc.Invoke(ctx, RagService_DeleteKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpsertDocument(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*UpsertDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_UpsertDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, RagService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) RetryDocument(ctx context.Context, in *RetryDocumentRequest, opts ...grpc.CallOption) (*DocumentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentStatus)
	err := c.cc.Invoke(ctx, RagService_RetryDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetDocumentStatus(ctx context.Context, in *GetDocumentStatusRequest, opts ...grpc.CallOption) (*DocumentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentStatus)
	err := c.cc.Invoke(ctx, RagService_GetDocumentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
//
// RagService RAG 检索与知识库管理服务。
type RagServiceServer interface {
	// Search 混合检索：向量 + 关键词双路召回，返回带来源引用的 chunk 列表。
	// kb_ids 为空 = 搜索全部知识库。
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// CreateKnowledgeBase 创建知识库。
	CreateKnowledgeBase(context.Context, *CreateKBRequest) (*KnowledgeBase, error)
	// ListKnowledgeBases 列出全部知识库（含文档统计）。
	ListKnowledgeBases(context.Context, *ListKBRequest) (*ListKBResponse, error)
	// UpdateKnowledgeBase 更新知识库名称/描述。
	UpdateKnowledgeBase(context.Context, *UpdateKBRequest) (*KnowledgeBase, error)
	// DeleteKnowledgeBase 删除知识库（连带文档与全部 chunk）。
	DeleteKnowledgeBase(context.Context, *DeleteKBRequest) (*DeleteKBResponse, error)
	// UpsertDocument 提交文档（原始字节落库待摄取）。同文件重传按 content_hash
	// 增量去重：内容未变则幂等跳过，变了则替换文档并重建其 chunk。
	UpsertDocument(context.Context, *UpsertDocumentRequest) (*UpsertDocumentResponse, error)
	// ListDocuments 列出知识库文档（含摄取状态，分页）。
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	// RetryDocument 手动重试摄取失败/已就绪的文档（重置 attempt 与退避，重新入队）。
	RetryDocument(context.Context, *RetryDocumentRequest) (*DocumentStatus, error)
	// DeleteDocument 删除文档（连带全部 chunk）。
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	// GetDocumentStatus 查询单个文档摄取状态。
	GetDocumentStatus(context.Context, *GetDocumentStatusRequest) (*DocumentStatus, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRagServiceServer) CreateKnowledgeBase(context.Context, *CreateKBRequest) (*KnowledgeBase, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedRagServiceServer) ListKnowledgeBases(context.Context, *ListKBRequest) (*ListKBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeBases not implemented")
}
func (UnimplementedRagServiceServer) UpdateKnowledgeBase(context.Context, *UpdateKBRequest) (*KnowledgeBase, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKnowledgeBase not implemented")
}
func (UnimplementedRagServiceServer) DeleteKnowledgeBase(context.Context, *DeleteKBRequest) (*DeleteKBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKnowledgeBase not implemented")
}
func (UnimplementedRagServiceServer) UpsertDocument(context.Context, *UpsertDocumentRequest) (*UpsertDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDocument not implemented")
}
func (UnimplementedRagServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedRagServiceServer) RetryDocument(context.Context, *RetryDocumentRequest) (*DocumentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryDocument not implemented")
}
func (UnimplementedRagServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedRagServiceServer) GetDocumentStatus(context.Context, *GetDocumentStatusRequest) (*DocumentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentStatus not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CreateKnowledgeBase(ctx, req.(*CreateKBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListKnowledgeBases(ctx, req.(*ListKBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpdateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpdateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpdateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpdateKnowledgeBase(ctx, req.(*UpdateKBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteKnowledgeBase(ctx, req.(*DeleteKBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpsertDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpsertDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpsertDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpsertDocument(ctx, req.(*UpsertDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_RetryDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).RetryDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_RetryDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).RetryDocument(ctx, req.(*RetryDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetDocumentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetDocumentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetDocumentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetDocumentStatus(ctx, req.(*GetDocumentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.v1.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _RagService_Search_Handler,
		},
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _RagService_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBases",
			Handler:    _RagService_ListKnowledgeBases_Handler,
		},
		{
			MethodName: "UpdateKnowledgeBase",
			Handler:    _RagService_UpdateKnowledgeBase_Handler,
		},
		{
			MethodName: "DeleteKnowledgeBase",
			Handler:    _RagService_DeleteKnowledgeBase_Handler,
		},
		{
			MethodName: "UpsertDocument",
			Handler:    _RagService_UpsertDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _RagService_ListDocuments_Handler,
		},
		{
			MethodName: "RetryDocument",
			Handler:    _RagService_RetryDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _RagService_DeleteDocument_Handler,
		},
		{
			MethodName: "GetDocumentStatus",
			Handler:    _RagService_GetDocumentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag/v1/rag.proto",
}
