// agent.proto —— Agent 会话与对话服务契约（P2-A）
//
// 本文件是对话域的唯一事实来源：agent-service 实现它，gateway 调用它。
//
// 设计要点：
//   - 非流式 Chat 用于不需要打字机效果的场景；StreamChat 用 server-streaming
//     逐事件下发（文本增量 / 工具调用 / 结束统计），gateway 转成 HTTP SSE；
//   - user_id 经 gRPC metadata（x-user-id）注入，请求体不含属主字段；
//   - 会话与消息持久化在 agent_db（见 migrations/agent）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.13.0
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_CreateSession_FullMethodName       = "/agent.v1.AgentService/CreateSession"
	AgentService_ListSessions_FullMethodName        = "/agent.v1.AgentService/ListSessions"
	AgentService_GetSession_FullMethodName          = "/agent.v1.AgentService/GetSession"
	AgentService_DeleteSession_FullMethodName       = "/agent.v1.AgentService/DeleteSession"
	AgentService_ListMessages_FullMethodName        = "/agent.v1.AgentService/ListMessages"
	AgentService_DeleteMessage_FullMethodName       = "/agent.v1.AgentService/DeleteMessage"
	AgentService_RenameSession_FullMethodName       = "/agent.v1.AgentService/RenameSession"
	AgentService_UpdateSessionConfig_FullMethodName = "/agent.v1.AgentService/UpdateSessionConfig"
	AgentService_ListTools_FullMethodName           = "/agent.v1.AgentService/ListTools"
	AgentService_ListResources_FullMethodName       = "/agent.v1.AgentService/ListResources"
	AgentService_Regenerate_FullMethodName          = "/agent.v1.AgentService/Regenerate"
	AgentService_StreamRegenerate_FullMethodName    = "/agent.v1.AgentService/StreamRegenerate"
	AgentService_SetActiveVersion_FullMethodName    = "/agent.v1.AgentService/SetActiveVersion"
	AgentService_CreateBranch_FullMethodName        = "/agent.v1.AgentService/CreateBranch"
	AgentService_Chat_FullMethodName                = "/agent.v1.AgentService/Chat"
	AgentService_StreamChat_FullMethodName          = "/agent.v1.AgentService/StreamChat"
	AgentService_SubmitToolResult_FullMethodName    = "/agent.v1.AgentService/SubmitToolResult"
	AgentService_MergeGuestSessions_FullMethodName  = "/agent.v1.AgentService/MergeGuestSessions"
	AgentService_UploadChatDocument_FullMethodName  = "/agent.v1.AgentService/UploadChatDocument"
	AgentService_AdminSessionStats_FullMethodName   = "/agent.v1.AgentService/AdminSessionStats"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService Agent 会话与对话服务。
type AgentServiceClient interface {
	// CreateSession 创建会话。
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// ListSessions 列出当前用户的会话（分页，按更新时间倒序）。
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// GetSession 获取会话详情（含属主校验，非本人返回 NOT_FOUND）。
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	// DeleteSession 删除会话（含其全部消息，属主校验）。
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// ListMessages 列出会话全部消息（seq 升序，含工具调用对，属主校验）。
	// 供前端"历史回看"与"重开浏览器恢复上下文"使用。
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	// DeleteMessage 删除"一轮完整对话"（属主校验）。
	// 从该消息所在轮（最近的 user 消息）开始，删除到下一轮 user 消息之前
	// 的全部消息（含该轮 user 消息、assistant 回答、工具调用对）——用户
	// 觉得某段对话无意义想整段清理时使用。删除后该会话若已无任何消息，
	// 会话自动软删（空会话不保留）。
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	// RenameSession 重命名会话（属主校验）。
	RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*RenameSessionResponse, error)
	// UpdateSessionConfig 更新会话配置（工具权限 / 思考模式等，属主校验）。
	UpdateSessionConfig(ctx context.Context, in *UpdateSessionConfigRequest, opts ...grpc.CallOption) (*UpdateSessionConfigResponse, error)
	// ListTools 列出当前默认可用工具集（名称 + 描述），供前端渲染"工具权限"开关。
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// ListResources 列出普通用户可见的资源清单（能力 + 技能）。
	// 只含 id/名称/说明，不含任何工具名与技能代码（阶段1·权限分层）；
	// 勾选结果存入 SessionConfig.enabled_resources，服务端翻译为工具白名单。
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	// Regenerate 重新生成某轮的回答（属主校验）。
	// 旧版本回答保留（隐藏，可经 SetActiveVersion 切回），该轮之后的旧分支
	// 被截断（隐藏）；新回答以新版本号落库。
	Regenerate(ctx context.Context, in *RegenerateRequest, opts ...grpc.CallOption) (*RegenerateResponse, error)
	// StreamRegenerate 流式重新生成某轮的回答（版本语义同 Regenerate）。
	// 正文增量/思考/工具调用与编排进度均经 SSE 逐事件下发；结束时带统计。
	StreamRegenerate(ctx context.Context, in *RegenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatEvent], error)
	// SetActiveVersion 切换某轮的活跃版本（属主校验）。
	// 隐藏该轮其它版本，并截断（隐藏）该轮之后的全部旧分支消息。
	SetActiveVersion(ctx context.Context, in *SetActiveVersionRequest, opts ...grpc.CallOption) (*SetActiveVersionResponse, error)
	// CreateBranch 基于当前上下文创建分支会话（属主校验）。
	// 复制"到分支点为止"的历史（含分支点所在轮），新会话可继续对话。
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	// Chat 非流式对话：加载历史 → framework.Run → 消息落库 → 返回。
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// StreamChat 流式对话：文本增量逐事件下发，结束时带统计。
	StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatEvent], error)
	// SubmitToolResult 回填外部工具调用的执行结果（阶段3·本地工具代理）。
	// 桌面客户端在完成本地工具执行后调用，唤醒挂起等待的会话继续推理。
	// user_id 经 metadata 注入并做属主校验。
	SubmitToolResult(ctx context.Context, in *SubmitToolResultRequest, opts ...grpc.CallOption) (*SubmitToolResultResponse, error)
	// MergeGuestSessions 登录后把游客阶段的会话合并到当前账号（阶段2·游客模式）。
	// 游客会话以合成负 user_id 落库（见 auth.GuestUserID）；登录成功后前端
	// 携带原游客 ID 调用本接口，把该命名空间下全部会话（含其消息）转移给
	// 当前账号——"游客会话不保留、登录后合并"。调用方必须是真实用户。
	MergeGuestSessions(ctx context.Context, in *MergeGuestSessionsRequest, opts ...grpc.CallOption) (*MergeGuestSessionsResponse, error)
	// UploadChatDocument 上传文档供智能体理解（模块二）。
	// 解析复用 rag ingest 管线（md/txt/html/xlsx 原生；pdf/docx/pptx 委托沙盒），
	// 解析全文落盘用户工作区 chat-files/<session_id>/，并注入一条限长 user
	// 消息进会话历史（后续轮次可持续追问）。属主校验同会话。
	UploadChatDocument(ctx context.Context, in *UploadChatDocumentRequest, opts ...grpc.CallOption) (*UploadChatDocumentResponse, error)
	// AdminSessionStats 管理端会话统计（数据管理模块，仅最高超管可见）。
	// 由 gateway adminsvc 经鉴权后调用（内网可信转发）；返回时间窗口内的
	// 会话聚合：按日新建会话数 + 按智能体域分布 + 全量累计会话数。
	// 调用者身份仍经 metadata x-user-id 注入，避免裸 gRPC 匿名直连。
	AdminSessionStats(ctx context.Context, in *AdminSessionStatsRequest, opts ...grpc.CallOption) (*AdminSessionStatsResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*RenameSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_RenameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateSessionConfig(ctx context.Context, in *UpdateSessionConfigRequest, opts ...grpc.CallOption) (*UpdateSessionConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateSessionConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Regenerate(ctx context.Context, in *RegenerateRequest, opts ...grpc.CallOption) (*RegenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateResponse)
	err := c.cc.Invoke(ctx, AgentService_Regenerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamRegenerate(ctx context.Context, in *RegenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamRegenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegenerateRequest, StreamChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamRegenerateClient = grpc.ServerStreamingClient[StreamChatEvent]

func (c *agentServiceClient) SetActiveVersion(ctx context.Context, in *SetActiveVersionRequest, opts ...grpc.CallOption) (*SetActiveVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveVersionResponse)
	err := c.cc.Invoke(ctx, AgentService_SetActiveVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AgentService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChatRequest, StreamChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamChatClient = grpc.ServerStreamingClient[StreamChatEvent]

func (c *agentServiceClient) SubmitToolResult(ctx context.Context, in *SubmitToolResultRequest, opts ...grpc.CallOption) (*SubmitToolResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitToolResultResponse)
	err := c.cc.Invoke(ctx, AgentService_SubmitToolResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) MergeGuestSessions(ctx context.Context, in *MergeGuestSessionsRequest, opts ...grpc.CallOption) (*MergeGuestSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeGuestSessionsResponse)
	err := c.cc.Invoke(ctx, AgentService_MergeGuestSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UploadChatDocument(ctx context.Context, in *UploadChatDocumentRequest, opts ...grpc.CallOption) (*UploadChatDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadChatDocumentResponse)
	err := c.cc.Invoke(ctx, AgentService_UploadChatDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AdminSessionStats(ctx context.Context, in *AdminSessionStatsRequest, opts ...grpc.CallOption) (*AdminSessionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSessionStatsResponse)
	err := c.cc.Invoke(ctx, AgentService_AdminSessionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService Agent 会话与对话服务。
type AgentServiceServer interface {
	// CreateSession 创建会话。
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// ListSessions 列出当前用户的会话（分页，按更新时间倒序）。
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// GetSession 获取会话详情（含属主校验，非本人返回 NOT_FOUND）。
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	// DeleteSession 删除会话（含其全部消息，属主校验）。
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// ListMessages 列出会话全部消息（seq 升序，含工具调用对，属主校验）。
	// 供前端"历史回看"与"重开浏览器恢复上下文"使用。
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// DeleteMessage 删除"一轮完整对话"（属主校验）。
	// 从该消息所在轮（最近的 user 消息）开始，删除到下一轮 user 消息之前
	// 的全部消息（含该轮 user 消息、assistant 回答、工具调用对）——用户
	// 觉得某段对话无意义想整段清理时使用。删除后该会话若已无任何消息，
	// 会话自动软删（空会话不保留）。
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	// RenameSession 重命名会话（属主校验）。
	RenameSession(context.Context, *RenameSessionRequest) (*RenameSessionResponse, error)
	// UpdateSessionConfig 更新会话配置（工具权限 / 思考模式等，属主校验）。
	UpdateSessionConfig(context.Context, *UpdateSessionConfigRequest) (*UpdateSessionConfigResponse, error)
	// ListTools 列出当前默认可用工具集（名称 + 描述），供前端渲染"工具权限"开关。
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// ListResources 列出普通用户可见的资源清单（能力 + 技能）。
	// 只含 id/名称/说明，不含任何工具名与技能代码（阶段1·权限分层）；
	// 勾选结果存入 SessionConfig.enabled_resources，服务端翻译为工具白名单。
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	// Regenerate 重新生成某轮的回答（属主校验）。
	// 旧版本回答保留（隐藏，可经 SetActiveVersion 切回），该轮之后的旧分支
	// 被截断（隐藏）；新回答以新版本号落库。
	Regenerate(context.Context, *RegenerateRequest) (*RegenerateResponse, error)
	// StreamRegenerate 流式重新生成某轮的回答（版本语义同 Regenerate）。
	// 正文增量/思考/工具调用与编排进度均经 SSE 逐事件下发；结束时带统计。
	StreamRegenerate(*RegenerateRequest, grpc.ServerStreamingServer[StreamChatEvent]) error
	// SetActiveVersion 切换某轮的活跃版本（属主校验）。
	// 隐藏该轮其它版本，并截断（隐藏）该轮之后的全部旧分支消息。
	SetActiveVersion(context.Context, *SetActiveVersionRequest) (*SetActiveVersionResponse, error)
	// CreateBranch 基于当前上下文创建分支会话（属主校验）。
	// 复制"到分支点为止"的历史（含分支点所在轮），新会话可继续对话。
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	// Chat 非流式对话：加载历史 → framework.Run → 消息落库 → 返回。
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// StreamChat 流式对话：文本增量逐事件下发，结束时带统计。
	StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatEvent]) error
	// SubmitToolResult 回填外部工具调用的执行结果（阶段3·本地工具代理）。
	// 桌面客户端在完成本地工具执行后调用，唤醒挂起等待的会话继续推理。
	// user_id 经 metadata 注入并做属主校验。
	SubmitToolResult(context.Context, *SubmitToolResultRequest) (*SubmitToolResultResponse, error)
	// MergeGuestSessions 登录后把游客阶段的会话合并到当前账号（阶段2·游客模式）。
	// 游客会话以合成负 user_id 落库（见 auth.GuestUserID）；登录成功后前端
	// 携带原游客 ID 调用本接口，把该命名空间下全部会话（含其消息）转移给
	// 当前账号——"游客会话不保留、登录后合并"。调用方必须是真实用户。
	MergeGuestSessions(context.Context, *MergeGuestSessionsRequest) (*MergeGuestSessionsResponse, error)
	// UploadChatDocument 上传文档供智能体理解（模块二）。
	// 解析复用 rag ingest 管线（md/txt/html/xlsx 原生；pdf/docx/pptx 委托沙盒），
	// 解析全文落盘用户工作区 chat-files/<session_id>/，并注入一条限长 user
	// 消息进会话历史（后续轮次可持续追问）。属主校验同会话。
	UploadChatDocument(context.Context, *UploadChatDocumentRequest) (*UploadChatDocumentResponse, error)
	// AdminSessionStats 管理端会话统计（数据管理模块，仅最高超管可见）。
	// 由 gateway adminsvc 经鉴权后调用（内网可信转发）；返回时间窗口内的
	// 会话聚合：按日新建会话数 + 按智能体域分布 + 全量累计会话数。
	// 调用者身份仍经 metadata x-user-id 注入，避免裸 gRPC 匿名直连。
	AdminSessionStats(context.Context, *AdminSessionStatsRequest) (*AdminSessionStatsResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAgentServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedAgentServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedAgentServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedAgentServiceServer) RenameSession(context.Context, *RenameSessionRequest) (*RenameSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSession not implemented")
}
func (UnimplementedAgentServiceServer) UpdateSessionConfig(context.Context, *UpdateSessionConfigRequest) (*UpdateSessionConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionConfig not implemented")
}
func (UnimplementedAgentServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedAgentServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedAgentServiceServer) Regenerate(context.Context, *RegenerateRequest) (*RegenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Regenerate not implemented")
}
func (UnimplementedAgentServiceServer) StreamRegenerate(*RegenerateRequest, grpc.ServerStreamingServer[StreamChatEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamRegenerate not implemented")
}
func (UnimplementedAgentServiceServer) SetActiveVersion(context.Context, *SetActiveVersionRequest) (*SetActiveVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveVersion not implemented")
}
func (UnimplementedAgentServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedAgentServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentServiceServer) StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedAgentServiceServer) SubmitToolResult(context.Context, *SubmitToolResultRequest) (*SubmitToolResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitToolResult not implemented")
}
func (UnimplementedAgentServiceServer) MergeGuestSessions(context.Context, *MergeGuestSessionsRequest) (*MergeGuestSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeGuestSessions not implemented")
}
func (UnimplementedAgentServiceServer) UploadChatDocument(context.Context, *UploadChatDocumentRequest) (*UploadChatDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadChatDocument not implemented")
}
func (UnimplementedAgentServiceServer) AdminSessionStats(context.Context, *AdminSessionStatsRequest) (*AdminSessionStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminSessionStats not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RenameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RenameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RenameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RenameSession(ctx, req.(*RenameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateSessionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateSessionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateSessionConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateSessionConfig(ctx, req.(*UpdateSessionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Regenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Regenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Regenerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Regenerate(ctx, req.(*RegenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamRegenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamRegenerate(m, &grpc.GenericServerStream[RegenerateRequest, StreamChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamRegenerateServer = grpc.ServerStreamingServer[StreamChatEvent]

func _AgentService_SetActiveVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetActiveVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SetActiveVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetActiveVersion(ctx, req.(*SetActiveVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamChat(m, &grpc.GenericServerStream[StreamChatRequest, StreamChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamChatServer = grpc.ServerStreamingServer[StreamChatEvent]

func _AgentService_SubmitToolResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitToolResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitToolResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitToolResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitToolResult(ctx, req.(*SubmitToolResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_MergeGuestSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeGuestSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).MergeGuestSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_MergeGuestSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).MergeGuestSessions(ctx, req.(*MergeGuestSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UploadChatDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChatDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UploadChatDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UploadChatDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UploadChatDocument(ctx, req.(*UploadChatDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AdminSessionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSessionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AdminSessionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AdminSessionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AdminSessionStats(ctx, req.(*AdminSessionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _AgentService_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _AgentService_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _AgentService_DeleteSession_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _AgentService_ListMessages_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _AgentService_DeleteMessage_Handler,
		},
		{
			MethodName: "RenameSession",
			Handler:    _AgentService_RenameSession_Handler,
		},
		{
			MethodName: "UpdateSessionConfig",
			Handler:    _AgentService_UpdateSessionConfig_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _AgentService_ListTools_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _AgentService_ListResources_Handler,
		},
		{
			MethodName: "Regenerate",
			Handler:    _AgentService_Regenerate_Handler,
		},
		{
			MethodName: "SetActiveVersion",
			Handler:    _AgentService_SetActiveVersion_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _AgentService_CreateBranch_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _AgentService_Chat_Handler,
		},
		{
			MethodName: "SubmitToolResult",
			Handler:    _AgentService_SubmitToolResult_Handler,
		},
		{
			MethodName: "MergeGuestSessions",
			Handler:    _AgentService_MergeGuestSessions_Handler,
		},
		{
			MethodName: "UploadChatDocument",
			Handler:    _AgentService_UploadChatDocument_Handler,
		},
		{
			MethodName: "AdminSessionStats",
			Handler:    _AgentService_AdminSessionStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRegenerate",
			Handler:       _AgentService_StreamRegenerate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChat",
			Handler:       _AgentService_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
